name: REG Model Retraining Job

on:
  schedule:
    # Run this job on the 1st of every month at 9 AM MST (16:00 UTC)
    - cron: "0 16 1 * *"
  workflow_dispatch:   # Enables manual trigger

jobs:
  retraining_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Scripts Sequentially
        run: |
          for script in Jobs/Retraining/scripts/*.py; do
            echo "Running $script..."
            python "$script"
            echo "Completed $script run..."
          done
          python "Jobs/Validation/scripts/price.py"

      - name: Run Python Scripts Sequentially
        run: |
          python "Jobs/Retraining/notebook/1. generation data processing.py"
          echo "Completed 1. generation data processing run..."
          python "Jobs/Retraining/notebook/2. feature engineering.py"
          echo "Completed 2. feature engineering run..."
          python "Jobs/Retraining/notebook/3. data cleaning.py"
          echo "Completed 3. data cleaning run..."
          python "Jobs/Retraining/notebook/4. LSTM modeling.py"
          echo "Completed 4. LSTM modeling run..."
          python "Jobs/Validation/notebook/1. plot predictions vs actual.py"
          echo "Completed 1. plot predictions vs actual run..."


      # - name: Run Jupyter Notebooks Sequentially
      #   run: |
      #     jupyter nbconvert --to notebook --execute "Jobs/Inferencing/notebook/1. feature engineering.ipynb" --inplace
      #     jupyter nbconvert --to notebook --execute "Jobs/Inferencing/notebook/2. data cleaning.ipynb" --inplace
      #     jupyter nbconvert --to notebook --execute "Jobs/Inferencing/notebook/3. model inferencing.ipynb" --inplace

      - name: Push Output Files (Optional)
        run: |
          git config --global user.name "kevakba"
          git config --global user.email "akbarikevin@gmail.com"
          git add .
          git commit -m "KA - Autorun retraining job results"
          git push origin main || echo "No changes to commit"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}